spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#  security:
#    user:
#      name: user
#      password: 12345
#      roles: ADMIN
